logging:
  level:
    root: debug

spring:
  security:
    user:
      name: admin
      password: admin
  main:
    allow-bean-definition-overriding: true


feign:
  hystrix:
    enabled: false

poc-oauth2:
  dados-receita:
    endpoint:
    method-consulta: